import os
import shutil
import subprocess

class ConfigParser:
    def __init__(self):
        self.config_path = os.path.expanduser("~/.config/i3/config")
        self.backup_path = self.config_path + ".bak"
        self.lines = []
        self.load_config()
        self.ensure_header_in_config()

    def load_config(self):
        """Reads the file and stores each line safely in memory."""
        self.lines = []
        if not os.path.exists(self.config_path):
            # Create an empty config if it doesn't exist to prevent errors
            self.lines = ["# i3 config generated by i3-EasyConfig\n"]
            return

        with open(self.config_path, "r") as f:
            self.lines = f.readlines()

    def ensure_header_in_config(self):
        """Add a managed header to the config on first run."""
        marker = "# i3-EasyConfig managed config"
        if any(marker in line for line in self.lines):
            return

        header = [
            marker + "\n",
            "# This config is managed by i3-EasyConfig.\n",
        ]

        self.lines = header + self.lines
        self.create_backup()
        self.write_config_direct()

    def create_backup(self):
        """Create an automatic backup before modifying the config."""
        os.makedirs(os.path.dirname(self.config_path), exist_ok=True)
        if os.path.exists(self.config_path):
            shutil.copy2(self.config_path, self.backup_path)

    def write_config_direct(self):
        """Write config directly to the i3 config path."""
        os.makedirs(os.path.dirname(self.config_path), exist_ok=True)
        with open(self.config_path, "w") as f:
            f.writelines(self.lines)

    def save(self, validate=True):
        """Save the current config, validating first if requested."""
        validation_failure = None
        if validate:
            success, message = self.validate_and_save()
            if success:
                return True, message
            validation_failure = message

        # Fallback direct save if validation fails or is skipped
        self.create_backup()
        try:
            self.write_config_direct()
        except PermissionError:
            if self.write_as_root():
                try:
                    subprocess.run(["i3-msg", "reload"], check=False)
                except FileNotFoundError:
                    pass
                return True, "Saved with root elevation"
            return False, "Permission denied. Root access is required to write the config."

        try:
            subprocess.run(["i3-msg", "reload"], check=False)
        except FileNotFoundError:
            pass

        if validation_failure:
            return True, f"Saved despite validation failure: {validation_failure}"

        return True, "Saved"

    def write_as_root(self):
        """Write the config using root elevation if normal write fails."""
        temp_path = "/tmp/i3_easyconfig_root_write"
        with open(temp_path, "w") as f:
            f.writelines(self.lines)

        runners = [
            ["pkexec", "cp", temp_path, self.config_path],
            ["sudo", "cp", temp_path, self.config_path],
        ]

        for runner in runners:
            try:
                subprocess.run(runner, check=True)
                return True
            except FileNotFoundError:
                continue
            except subprocess.CalledProcessError:
                continue
        return False

    def get_autostart_apps(self):
        """Extracts all exec lines for autostart apps."""
        apps = []
        for i, line in enumerate(self.lines):
            stripped = line.strip()
            if stripped.startswith("exec") or stripped.startswith("#exec"):
                apps.append({
                    "raw": stripped,
                    "index": i
                })
        return apps

    def toggle_line_comment(self, index, enable):
        """Toggle comment on a line. If enable=True, uncomment; if False, comment."""
        if index < len(self.lines):
            line = self.lines[index]
            stripped = line.strip()
            if enable:
                # Remove comment marker if present
                if stripped.startswith("#"):
                    self.lines[index] = stripped[1:].lstrip() + "\n"
                else:
                    self.lines[index] = line
            else:
                # Add comment marker if not present
                if not stripped.startswith("#"):
                    self.lines[index] = "# " + line.lstrip()
                else:
                    self.lines[index] = line

    def validate_and_save(self):
        """Runs i3 validation before saving to prevent crashes."""
        temp_path = "/tmp/i3_test_config"
        try:
            with open(temp_path, "w") as f:
                f.writelines(self.lines)

            validators = [
                (["i3-msg", "-C", "-c", temp_path], "i3-msg"),
                (["i3", "-C", "-c", temp_path], "i3"),
            ]

            validation_result = None
            for cmd, name in validators:
                try:
                    result = subprocess.run(cmd, capture_output=True, text=True)
                except FileNotFoundError:
                    continue

                if result.returncode == 0:
                    validation_result = result
                    break

                stderr = (result.stderr or "").lower()
                if "invalid option" in stderr or "unknown option" in stderr:
                    continue

                validation_result = result
                break

            if validation_result is None:
                return False, "No valid i3 validator found on this system."

            if validation_result.returncode != 0:
                return False, validation_result.stderr or validation_result.stdout

            self.create_backup()
            try:
                with open(self.config_path, "w") as f:
                    f.writelines(self.lines)
            except PermissionError:
                if not self.write_as_root():
                    return False, "Permission denied. Root access is required to write the config."

            try:
                subprocess.run(["i3-msg", "reload"], check=False)
            except FileNotFoundError:
                pass

            return True, "Success"
        except Exception as e:
            return False, str(e)
