import os
import subprocess

class ConfigParser:
    def __init__(self):
        self.config_path = os.path.expanduser("~/.config/i3/config")
        self.lines = []
        self.load_config()

    def load_config(self):
        """Reads the file and stores each line safely in memory."""
        self.lines = []
        if not os.path.exists(self.config_path):
            # Create an empty config if it doesn't exist to prevent errors
            self.lines = ["# i3 config generated by i3-EasyConfig\n"]
            return

        with open(self.config_path, "r") as f:
            self.lines = f.readlines()

    def get_autostart_apps(self):
        """Extracts all exec lines for autostart apps."""
        apps = []
        for i, line in enumerate(self.lines):
            stripped = line.strip()
            if stripped.startswith("exec") or stripped.startswith("#exec"):
                apps.append({
                    "raw": stripped,
                    "index": i
                })
        return apps

    def toggle_line_comment(self, index, enable):
        """Toggle comment on a line. If enable=True, uncomment; if False, comment."""
        if index < len(self.lines):
            line = self.lines[index]
            stripped = line.strip()
            if enable:
                # Remove comment marker if present
                if stripped.startswith("#"):
                    self.lines[index] = stripped[1:].lstrip() + "\n"
                else:
                    self.lines[index] = line
            else:
                # Add comment marker if not present
                if not stripped.startswith("#"):
                    self.lines[index] = "# " + line.lstrip()
                else:
                    self.lines[index] = line

    def validate_and_save(self):
        """Runs i3 validation before saving to prevent crashes."""
        temp_path = "/tmp/i3_test_config"
        try:
            with open(temp_path, "w") as f:
                f.writelines(self.lines)

            # Test the syntax using i3's built-in check
            result = subprocess.run(["i3-msg", "-C", "-c", temp_path], capture_output=True, text=True)

            if result.returncode == 0:
                with open(self.config_path, "w") as f:
                    f.writelines(self.lines)
                subprocess.run(["i3-msg", "reload"])
                return True, "Success"
            else:
                return False, result.stderr
        except Exception as e:
            return False, str(e)
